title: Sobre la naturaleza
author: gonzalo123
email: gonzalo123@domain.com
description: ... o del devemir

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md

footer_icons:
- username: @gonzalo123
  url: https://twitter.com/gonzalo123

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
