title: Sobre la naturaleza
author: Gonzalo Ayuso
email: gonzalo123@domain.com
description: o del devemir
twitter_username: gonzalo123
twitter_url: https://twitter.com/gonzalo123

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%-d/%m/%Y"
  date_format_short: "%m %-d"

header_pages:
- about.md
- posts.md

paginate: 7

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
